### ISSUE TITLE
Build / Link error

### ISSUE THREAD

**Issue by olavt** [microsoftgraph/ios-swift-connect-rest-sample#13]
I have tried to run the sample, but I got a linker error:

ld: warning: directory not found for option '-L/Users/olavt/Library/Developer/Xcode/DerivedData/O365-iOS-Microsoft-Graph-Connect-Swift-ffsucrmfywtpmveyxksredlofoch/Build/Products/Debug-iphonesimulator/ADALiOS'

The ADALiOS directory does not exist, but the parent does. I think I followed all the instructions.

**Comment by JohnMAustin78** [comment]
Hi there,
We've refreshed the Swift sample to use the MSAL authentication library for iOS. The MSAL library is obtained using Carthage instead of CocoaPods. Please update your local repository from the master branch of this repository to get these changes.  Let us know if you still have problems

John
